  const menuItems = [
    { id: 1, name: "Burger", category: "main", price: 50, available: false },
    { id: 2, name: "Salad", category: "salad", price: 30, available: true },
    {
      id: 3,
      name: "Grilled Chicken",
      category: "main",
      price: 75,
      available: true,
    },
    {
      id: 4,
      name: "Caesar Salad",
      category: "salad",
      price: 35,
      available: true,
    },
    {
      id: 5,
      name: "Spring Rolls",
      category: "appetizer",
      price: 25,
      available: true,
    },
    {
      id: 6,
      name: "Mozzarella Sticks",
      category: "appetizer",
      price: 20,
      available: false,
    },
    {
      id: 7,
      name: "Chocolate Lava Cake",
      category: "dessert",
      price: 40,
      available: true,
    },
    {
      id: 8,
      name: "Cheesecake",
      category: "dessert",
      price: 35,
      available: true,
    },
    {
      id: 9,
      name: "Iced Lemonade",
      category: "beverage",
      price: 15,
      available: true,
    },
    {
      id: 10,
      name: "Mango Smoothie",
      category: "beverage",
      price: 20,
      available: false,
    },
    {
      id: 11,
      name: "Pasta Carbonara",
      category: "main",
      price: 65,
      available: true,
    },
    {
      id: 12,
      name: "Greek Salad",
      category: "salad",
      price: 28,
      available: true,
    },
  ];
  const inventoryData = [
    {
      id: 1,
      name: "Bread",
      quantity: 10,
      unit: "piece",
      minQuantity: 5,
      status: "Available",
    },
    {
      id: 2,
      name: "Meat",
      quantity: 5,
      unit: "kg",
      minQuantity: 3,
      status: "Available",
    },
    {
      id: 3,
      name: "Cheese",
      quantity: 0,
      unit: "kg",
      minQuantity: 2,
      status: "Out",
    },
    {
      id: 4,
      name: "Lettuce",
      quantity: 8,
      unit: "piece",
      minQuantity: 4,
      status: "Available",
    },
    {
      id: 5,
      name: "Tomato",
      quantity: 15,
      unit: "piece",
      minQuantity: 6,
      status: "Available",
    },
  ];
  const categoryData = [
    {
      id: 1,
      name: "Main",
    },
    {
      id: 2,
      name: "Salad",
    },
    {
      id: 3,
      name: "Appetizer",
    },
  ];
export default {  menuItems, inventoryData,categoryData};